// Generated by CoffeeScript 1.3.3
(function() {
  var exec, fs, gifs, im, io, models, sys, uuid, _;

  io = require('socket.io').listen(8080);

  fs = require('fs');

  im = require('imagemagick');

  uuid = require('node-uuid');

  sys = require('sys');

  exec = require('child_process').exec;

  _ = require('underscore');

  models = require('./models');

  gifs = [];

  io.sockets.on('connection', function(socket) {
    socket.on('newGif', function(data) {
      var gif;
      gif = new models.GIF(data.numShots, socket, data.FPS);
      gifs.push(gif);
      return socket.emit('newGifReady', {
        gifId: gif.id
      });
    });
    return socket.on('newSnapshot', function(snapData) {
      var gif;
      gif = _(gifs).findWhere({
        id: snapData.gifId
      });
      if (gif) {
        return gif.addSnapshot(snapData);
      } else {
        return socket.emit('error');
      }
    });
  });

}).call(this);
