// Generated by CoffeeScript 1.3.3
(function() {
  var fs, im, io, writeFile;

  io = require('socket.io').listen(8080);

  fs = require('fs');

  im = require('imagemagick');

  io.sockets.on('connection', function(socket) {
    var expectedImages, imagesReceived;
    expectedImages = null;
    imagesReceived = null;
    socket.on('numImages', function(data) {
      return expectedImages = data.numImages;
    });
    return socket.on('image', function(data) {
      var imgData;
      imgData = data.contents.replace(/^data:image\/jpeg;base64,/, "");
      writeFile(imgData, data.imgNum);
      imagesReceived += 1;
      if (imagesReceived >= expectedImages) {
        return im.convert(['*.jpg', '-loop', '0', 'animation.gif']);
      }
    });
  });

  writeFile = function(data, imgNum) {
    return fs.writeFile("file" + imgNum + ".jpg", data, 'base64', function(err) {
      if (err) {
        return console.log('File could not be saved.');
      } else {
        return console.log('File saved.');
      }
    });
  };

}).call(this);
