// Generated by CoffeeScript 1.3.3
(function() {
  var IMGUR_API_KEY, fs, im, imgur, io, postImageToImgur, writeFile;

  IMGUR_API_KEY = "652deb70e66249c7046971f0850f144d";

  io = require('socket.io').listen(8080);

  fs = require('fs');

  im = require('imagemagick');

  imgur = require('imgur');

  imgur.setKey(IMGUR_API_KEY);

  postImageToImgur = function(filename) {
    return imgur.upload(filename, function(response) {
      return console.log(response.links.original);
    });
  };

  io.sockets.on('connection', function(socket) {
    var expectedImages, imagesReceived;
    expectedImages = null;
    imagesReceived = null;
    socket.on('numImages', function(data) {
      return expectedImages = data.numImages;
    });
    return socket.on('image', function(data) {
      var imgData;
      imgData = data.contents.replace(/^data:image\/jpeg;base64,/, "");
      writeFile(imgData, data.imgNum);
      imagesReceived += 1;
      if (imagesReceived >= expectedImages) {
        imagesReceived = 0;
        expectedImages = 0;
        return im.convert(['*.jpg', '-loop', '0', 'animation.gif'], function(err) {
          if (err) {
            throw err;
          }
          return postImageToImgur('animation.gif');
        });
      }
    });
  });

  writeFile = function(data, imgNum) {
    return fs.writeFile("file" + imgNum + ".jpg", data, 'base64', function(err) {
      if (err) {
        return console.log('File could not be saved.');
      } else {
        return console.log('File saved.');
      }
    });
  };

}).call(this);
