// Generated by CoffeeScript 1.3.3
(function() {
  var dl, fs, io, writeFile;

  io = require('socket.io').listen(5001);

  dl = require('delivery');

  fs = require('fs');

  io.sockets.on('connection', function(socket) {
    return socket.on('image', function(data) {
      var imgData;
      imgData = data.contents.replace(/^data:image\/jpeg;base64,/, "");
      return writeFile(imgData, data.imgNum);
    });
  });

  writeFile = function(data, imgNum) {
    return fs.writeFile("file" + imgNum + ".jpg", data, 'base64', function(err) {
      if (err) {
        return console.log('File could not be saved.');
      } else {
        return console.log('File saved.');
      }
    });
  };

}).call(this);
